import type { Metadata } from "next";
import { Noto_Sans, Noto_Serif, Noto_Sans_TC } from 'next/font/google';

import "../public/css/globals.css";

// Load Noto Sans (sans-serif font)
const notoSans = Noto_Sans({
    subsets: ['latin', 'latin-ext'],
    weight: ['400', '500', '600', '700'],
    variable: '--font-noto-sans',
    display: 'swap'
});

// Load Noto Serif (serif font)
const notoSerif = Noto_Serif({
    subsets: ['latin'],
    weight: ['400', '700'],
    variable: '--font-noto-serif',
    display: 'swap'
});

// Load Noto Sans TC (Traditional Chinese)
const notoSansTC = Noto_Sans_TC({
    subsets: ['latin'],
    weight: ['400', '500', '700'],
    variable: '--font-noto-sans-tc',
    display: 'swap'
});

export const metadata: Metadata = {
  title: "Frist Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${notoSans.variable} ${notoSansTC.variable} ` }>
        <body className="iweby">
            <div className="iweby-viewer">
                {children}
            </div>
        </body>
    </html>
  );
}
